### ISSUE TITLE
Bar Color Glitch

### ISSUE THREAD

**Issue by ghost** [Sticklord/oUF_Abu#13]
One on the recent patches in between 7.0 and Legion has made all of the bar colors turn green. This includes secondary resource bars as well as cast bars. I've tried reinstalling and messing around with the config, but nothing has worked. Are other people having this problem?

Let me know if you need more info.

**Comment by Sticklord** [comment]
Hey, I don't have this issue. Are you using a legion compatible version of oUF?

**Comment by Reeno121** [comment]
I ended up deleting my cache and WTF folders. That fixed the problem. Sorry!
