### ISSUE TITLE
cast bar different colors

### ISSUE THREAD

**Issue by ggiovannelli** [Sticklord/oUF_Abu#14]
Hi sticklord.

Should be possible to use different colors for castbars ? 

The actual light red and dark yellow for interruptible and non-interruptible  casts are sometimes too difficult to understand fast.

Probably a grey bar for non-interruptible  and a red for interruptible cast would be much better. 
Or you prefer a color  settings in Unit Specific tab :) ....

Thanks

**Comment by ggiovannelli** [comment]
I checked right now and the bars are class colored :)
I'd like to have bars non class-colored and very different colors  for interruptible and non-interruptible casts :)

Thanks again

**Comment by Sticklord** [comment]
Yeah, your castbar is classcolored, enemies' castbar is red i think. Here you can see the logic behind the colors: https://github.com/Sticklord/oUF_Abu/blob/master/Elements/Castbars.lua#L243

But yeah I like the dark yellow so I'm gonna keep it, but its a good idea to have an option for this in the config. I just can't be arsed to do this now, but I'll keep this issue open in case I'm very very bored once!

**Comment by ggiovannelli** [comment]
Hi sticklord,
this will be fine. 

I think the red bar is very similar also to dk class color and the yellow is very similar to druid class color and in the intense fight sometimes happens to misunderstand them often. 

What I really like is so to have 2 very different colors (don't care which ones :) so we can understand instant if the cast can be interrupted or not.

Thanks for attention :)
