### ISSUE TITLE
Frames dissapearing

### ISSUE THREAD

**Issue by Likusmydikus** [Sticklord/oUF_Abu#16]
When on hunter using any vehicle like sitting within guns while owning pet, main frame and pet frame will switch, switching me with pet and my char frame with avatar of vehicle, thus loosing pet frame.

Then on vehicle exit, I would get stuck both in pet and character frame, making pet frame being lost. To fix I was forced to /reload.

**Comment by Sticklord** [comment]
Yeah I've known about this one, its an oUF issue. Added a hack in my layout until it got fixed in a fan update of oUF. Then they released oUF without a fix for this and i had removed my fix so that's where we are now. You can see here:https://github.com/oUF-wow/oUF/pull/298

**Comment by Likusmydikus** [comment]
so you fixed this again or?

**Comment by Sticklord** [comment]
fixed with https://github.com/Sticklord/oUF_Abu/commit/ae78a3829e6f8b7ef67d178473b04f435226ba23
