### ISSUE TITLE
Level number field mashups with icon of combat

### ISSUE THREAD

**Issue by Likusmydikus** [Sticklord/oUF_Abu#17]
While in combat, level number is displayed behind crossed swords instead of disappearing, making circle ugly and messed up, rendering it unreadable of any info.

**Comment by Sticklord** [comment]
Yeah i know, never gotten around to fix it. But since its here i guess i have to!

**Comment by Likusmydikus** [comment]
thank you for your work! Can you also move the font on right or at least give us an option to make it smaller as numbers touch frame circle several times?

**Comment by Sticklord** [comment]
Fixed with https://github.com/Sticklord/oUF_Abu/commit/48c764577944a2a9193f2e1afcc0e3bc760036e5
