### ISSUE TITLE
Offline group members on join

### ISSUE THREAD

**Issue by Likusmydikus** [Sticklord/oUF_Abu#18]
Every time I invited someone to party they appeared with "thunder" aka offline mark on their avatar(class icon in my case). I did /reload and then it shows correctly.

**Comment by Sticklord** [comment]
Thanks for all your reports. I'll look into this one.

**Comment by Sticklord** [comment]
Hopefully fixed with https://github.com/Sticklord/oUF_Abu/commit/be2e99bc3bfdfce60fd3bb94ae1bec6fe790efae
