### ISSUE TITLE
Movement skills change class icon in character frame

### ISSUE THREAD

**Issue by Likusmydikus** [Sticklord/oUF_Abu#20]
When I get Posthaste from my talent, class icon changes to Posthaste's icon. I think same occurs when someone else gives me speed/movement buff.

**Comment by Sticklord** [comment]
It's supposed to do this. Same thing as when you get cheap shotted by a rogue and it displays on your portrait.

**Comment by Likusmydikus** [comment]
any way to turn it off?

**Comment by Sticklord** [comment]
Turn off portrait timers in the config

**Comment by Likusmydikus** [comment]
but I want my character to has class icon instead of its portrait. I just don't want skill to replace it while in combat.

**Comment by Sticklord** [comment]
Yeah turn off the option Show protrait timers, keep Enable class portrait turned on
