### ISSUE TITLE
oUF_AbuPlayer:SetSize()

### ISSUE THREAD

**Issue by ghost** [Sticklord/oUF_Abu#29]
```
1x [ADDON_ACTION_BLOCKED] AddOn 'oUF' tried to call the protected function 'oUF_AbuPlayer:SetSize()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `SetSize'
oUF_Abu\Layout.lua:231: in function <oUF_Abu\Layout.lua:227>
(tail call): ?

Locals:
```

This happens when you come off a vehicle after being in combat it seems. This might be the best way to reproduce this.

**Comment by Sticklord** [comment]
Godamnit, I fix something and I break something. I know why this happens is though, I'll fix it when i get time. Thanks!

**Comment by Kkthnx** [comment]
Any update on this? I hope all is well man.
